services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5440:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
  backend:
    build: 
      context: .
      dockerfile: Dockerfile  
    container_name: gql
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - db
    working_dir: /root
    restart: always