version: "3"
services:

  postgres:
    image: postgres:alpine
    container_name: test
    ports:
      - 6432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres