// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewComment struct {
	PostID int    `json:"postID"`
	User   string `json:"user"`
	Text   string `json:"text"`
}

type NewPost struct {
	User          string `json:"user"`
	Title         string `json:"title"`
	Content       string `json:"content"`
	AllowComments *bool  `json:"allowComments,omitempty"`
}

type Query struct {
}
